import { Router } from 'express';
import { createAllergiesRouter } from '../allergies';
import { createAppointmentsRouter } from '../appointments';
import { createClinicalNotesRouter } from '../clinical-notes';
import { createClinicalResultsRouter } from '../clinical-results';
import { createConditionsRouter } from '../conditions';
import { createDailyEntriesRouter } from '../daily-entries';
import { createDoctorsRouter } from '../doctors';
import { createFeedFormulasRouter } from '../feed-formulas';
import { createFeedLogsRouter } from '../feed-logs';
import { createFocusAreasRouter } from '../focus-areas';
import { createHealthImportsRouter } from '../health-imports';
import { createHospitalsRouter } from '../hospitals';
import { createInsuranceCoveragesRouter } from '../insurance-coverages';
import { createLlmModelsRouter } from '../llm-models';
import { createMedicalHistoryEventsRouter } from '../medical-history-events';
import { createMedicationsRouter } from '../medications';
import { createReferralsRouter } from '../referrals';
import { createResearchNotesRouter } from '../research-notes';
import { createSpeechTherapyConsumptionRouter } from '../speech-therapy-consumption';
import { createSpecialtiesRouter } from '../specialties';
import { createSymptomLogsRouter } from '../symptom-logs';
import { createTherapyExerciseImportAiExchangesRouter } from '../therapy-exercise-import-ai-exchanges';
import { createTherapyExerciseImportsRouter } from '../therapy-exercise-imports';
import { createTherapyExerciseLogsRouter } from '../therapy-exercise-logs';
import { createTherapyExercisesRouter } from '../therapy-exercises';
import { createVitalSignsRouter } from '../vital-signs';

/**
 * Aggregates all my-health data routers under /api/data.
 */
export const createMyHealthDataService = (): Router => {
  const router = Router();
  router.use('/hospitals', createHospitalsRouter());
  router.use('/specialties', createSpecialtiesRouter());
  router.use('/doctors', createDoctorsRouter());
  router.use('/appointments', createAppointmentsRouter());
  router.use('/focus-areas', createFocusAreasRouter());
  router.use('/daily-entries', createDailyEntriesRouter());
  router.use('/medical-history-events', createMedicalHistoryEventsRouter());
  router.use('/symptom-logs', createSymptomLogsRouter());
  router.use('/research-notes', createResearchNotesRouter());
  router.use('/allergies', createAllergiesRouter());
  router.use('/medications', createMedicationsRouter());
  router.use('/conditions', createConditionsRouter());
  router.use('/vital-signs', createVitalSignsRouter());
  router.use('/clinical-results', createClinicalResultsRouter());
  router.use('/clinical-notes', createClinicalNotesRouter());
  router.use('/referrals', createReferralsRouter());
  router.use('/insurance-coverages', createInsuranceCoveragesRouter());
  router.use('/health-imports', createHealthImportsRouter());
  router.use('/therapy-exercises', createTherapyExercisesRouter());
  router.use('/therapy-exercise-logs', createTherapyExerciseLogsRouter());
  router.use('/speech-therapy-consumption', createSpeechTherapyConsumptionRouter());
  router.use('/therapy-exercise-imports', createTherapyExerciseImportsRouter());
  router.use('/therapy-exercise-import-ai-exchanges', createTherapyExerciseImportAiExchangesRouter());
  router.use('/llm-models', createLlmModelsRouter());
  router.use('/feed-formulas', createFeedFormulasRouter());
  router.use('/feed-logs', createFeedLogsRouter());
  return router;
};
